id: github-workflow-run-values
language: Yaml
rule:
  all:
    - pattern: '- run: $RUN'
    - inside:
        pattern: 'steps: $$$STEPS'
        stopBy: end
    - inside:
        pattern: 'jobs: $$$JOBS'
        stopBy: end
